
baseURL = "https://rescuepang.com/"
languageCode = "en-us"
title = "Rescuepang"
theme = "ananke"

enableRobotsTXT = true
buildFuture = false

[pagination]
pagerSize = 10

[params]
  mainSections = ["posts"]
